os: linux
env:
  jobs:
  - NAME=caribbean_basin-ssh-2h
  - NAME=curacao-2h
  - NAME=curacao_regional-2h
  - NAME=sababank-2h
  - NAME=sintmaarten-2h
  - NAME=caribbean_basin-2h
  - NAME=caribbean_basin-daily
  - NAME=caribbean_basin-ssh-daily
  - NAME=curacao-daily
  - NAME=curacao_regional-daily
  - NAME=sababank-daily
  - NAME=sintmaarten-daily
  global:
    #secure: heGKpV7TD4HhZfMbrJR8KEans5vywQzMS6HExcCWtA8+/pItu4kepVaqNasnNX0Mkjizg3sKN4uoh+kH66bfpoXf7kjFlnmRjhnHB4QvnTY0iuYVnu8Up0dX4yQv7kWXcbCD0ENmZv+WbeoBBRb5aTsCHTHTEx3rUkduZ7d/Pd/zAfBGnWtWPxhngR2k1JPRGM6w2t/UeZE/naFYduB041kMVKDuWsWIf1MFGBdJdp+4/WtZlreYKCd+PazKD7Giklg/4LjVciom2keILBCbtjhDv810VSs50Z8BHqON2ft93Z02wIlWVTqVotYLcB+Ah7daSMjapUb07HRSGIXyY/dIxVKILve0DSBlN5GVsYbqvp/9eiE1GjA4TXQBG5xGv8QTep8dQFSE19esMQXs8WfetP3xDQ/ciEaNZoFSehgP7vZhTXLiky7I4JGzJJTuWHwPWXUwF22KC6t2x7i9Bgy8Bp8hv0qvDdSf1ZmAjLsxCECpe6eeMvGSP8/pJggmB1p4vL7C77xcJ7KWULhJELGU/MoRf+G7XiGSTMXzcgT1tkt6Xw+CGPDbQFPs+HtHcpLsATaftIkX0OT4tMj0xuGQnicy5Ihwz14aLa6zuk3jRdy7Lt+FWXqCLIQxnt3ZC11AwCNsvzTqUlcFioj9xRh84nC9gum3WozXLVos+C0=
    secure: "FE16JiyAV7aAdQfF41Yy502sv+d9PMf7Ijw1c01Bfev44TeuI/76mHdS+Jbb5Xr9cMr0AZjt1Zlpk45aG2UWxVrVpdf7f52q1c1fWeUq3/mT5wLv10ULSMN/+WeuI3+VZmFP9WQtgZJlv8DE31peu3tvKmDDRlVsjQ1G8rAuaa7ENIFjpXVmhtQSkcdNtbNX+W3AeTR9T7APTsWQVgmmpCPegKWjarE0ddBhWfh5eghfja5Ik+enVOT4hOBhrxHdSJMMnr2jteRmwsEhA5+4fDnJfyn36lvUBHIDrS6TV8+0DbwIL+uh+G3MS3y8Tr8+Src/PaIqxjQuM/O7dFof6RXeSs8tsQ8GfFOXkKrqvtG0ECscFmB7TcvheWPtfKUImYLXPsTae/glutGuKMUWdF0T55P2YlG94NjwChzcNYG+zlVg0JuoV3r3MOxuWH5tpLEmmXdOop2lTgC/ArzANPBG0nFEcYm+5hOnTaX58as8PMiOpRDbeuWckRq8yLZeYZTdhciLX8QvB0/vOt6svLhavaXtx1xHaNL48QQ895RixBBGHzFrIbHviVPrcLiVHAjnRpWI7oI+iVly6ySzUInXMxqc73OqWIWsTwoCuzt4lnovduDrH+/ys8RbrYrGuaqKjo3z0bCT0IukA+lgauXxhqZPsZ9BI5yONAsaJGQ="
services: docker
dist: bionic
language: python
before_install:
#- echo "${prowlkey}" | sed -e 's/\(.\)../\1--/g'
- openssl aes-256-cbc -K $encrypted_a64724db4394_key -iv $encrypted_a64724db4394_iv -in store.tar.enc -out store.tar -d
- tar xvf store.tar
#- echo user
#- echo ${po%%:*} | wc -c
#- echo ${po%%:*} | cut -c1-4
#- echo token
#- echo ${po##*:} | wc -c
#- echo ${po##*:} | cut -c1-4
#- curl -s --form-string "token=${po##*:}" --form-string "user=${po%%:*}" --form-string "title=Build begun" --form-string "message=Build $TRAVIS_JOB_NUMBER $TRAVIS_JOB_WEB_URL" --form-string "url_title=Open in Travis CI" --form-string "url=$TRAVIS_JOB_WEB_URL" https://api.pushover.net/1/messages.json
install: docker build -t caribbeanwatch -f Dockerfile --build-arg TRAVIS_JOB_NUMBER="$TRAVIS_JOB_NUMBER"
  .
script: docker run -a stdout -t caribbeanwatch /home/caribbeanwatch/src/pyRVPelagia64PE414Sababank_Current/update.py
  -j $TRAVIS_JOB_NUMBER -r $NAME
jobs:
  include:
  - stage: activate
    env: NAME=activate_media
    services: docker
    dist: bionic
    language: cpp
    before_install:
    - openssl aes-256-cbc -K $encrypted_a64724db4394_key -iv $encrypted_a64724db4394_iv -in store.tar.enc -out store.tar -d
    - tar xvf store.tar
    install: docker build -t caribbeanwatch -f Dockerfile --build-arg TRAVIS_JOB_NUMBER="$TRAVIS_JOB_NUMBER"
      .
    script: docker run -a stdout -t caribbeanwatch /home/caribbeanwatch/activate.sh
  - stage: deploy
    env: NAME=webpages
    services: docker
    dist: bionic
    language: python
    before_install:
    - openssl aes-256-cbc -K $encrypted_a64724db4394_key -iv $encrypted_a64724db4394_iv -in store.tar.enc -out store.tar -d
    - tar xvf store.tar
    install: docker build -t webpages -f Dockerfile_webupdate --build-arg TRAVIS_JOB_NUMBER="$TRAVIS_JOB_NUMBER"
      .
    script:
      - docker run -a stdout -t webpages ./update.sh "Automatic update to static site from travis CaribbeanWatch, jobid $TRAVIS_JOB_NUMBER" | tee $HOME/version
    after_success:
    - cat $HOME/version
    - echo '**********'
    - tail -n 1 $HOME/version
    #- wget -q -O - "http://prowl.weks.net/publicapi/add?apikey=${prowlkey}&priority=0&application=CARIBBEANWATCH&event=Build%20success&description=Build%20$(tail -n 1 $HOME/version)%20$TRAVIS_JOB_NUMBER%20$TRAVIS_JOB_WEB_URL"
    - curl -s --form-string "token=${po##*:}" --form-string "user=${po%%:*}" --form-string "title=Build success" --form-string "message=Build $(tail -n 1 $HOME/version) $TRAVIS_JOB_NUMBER" --form-string "url_title=Open in Travis CI" --form-string "url=$TRAVIS_JOB_WEB_URL" https://api.pushover.net/1/messages.json
    after_failure:
    #- wget -q -O - "http://prowl.weks.net/publicapi/add?apikey=${prowlkey}&priority=0&application=CARIBBEANWATCH&event=Build%20failure&description=Deploy%20$TRAVIS_JOB_NUMBER%20$TRAVIS_JOB_WEB_URL"
    # Doesn't appear to generate this - unless possibly last job fails?
    - curl -s --form-string "token=${po##*:}" --form-string "user=${po%%:*}" --form-string "title=Build failure" --form-string "message=Deploy $TRAVIS_JOB_NUMBER" --form-string "url_title=Open in Travis CI" --form-string "url=$TRAVIS_JOB_WEB_URL" https://api.pushover.net/1/messages.json
after_failure:
#- wget -q -O - "http://prowl.weks.net/publicapi/add?apikey=${prowlkey}&priority=0&application=CARIBBEANWATCH&event=Build%20failure&description=$TRAVIS_JOB_NUMBER%20$TRAVIS_JOB_WEB_URL"
# Too many of the following for each individual case, so commented out:
#- curl -s --form-string "token=${po##*:}" --form-string "user=${po%%:*}" --form-string "title=Build failure [TO BE QUIETENED 3]" --form-string "message=$TRAVIS_JOB_NUMBER" --form-string "url_title=Open in Travis CI" --form-string "url=$TRAVIS_JOB_WEB_URL" https://api.pushover.net/1/messages.json
stages:
- test
- combine
- activate
- deploy
notifications:
  email:
    recipients:
    - CaribbeanWatch@candylab.org
    on_success: always
    on_failure: always
