
# - NAME=Xenial-16.04-docker

cache:
  directories:
      - /home/caribbeanwatch/src/pyRVPelagia64PE414Sababank_Current/cache/
env:
  - REGION = caribbean_basin
  - REGION = curacao

services:
- docker
dist: xenial
language: cpp
before_install:
- openssl aes-256-cbc -K $encrypted_149a08f8ff66_key -iv $encrypted_149a08f8ff66_iv -in store.tar.enc -out store.tar -d
- tar xvf store.tar
script:
- if [ -f '/home/caribbeanwatch/src/pyRVPelagia64PE414Sababank_Current/cache/cache.tar.gz' ]; then gunzip -c '/home/caribbeanwatch/src/pyRVPelagia64PE414Sababank_Current/cache/cache.tar.gz' | docker load; fi
- docker run -v $PWD:/run -w="/run" -a stdout -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} /home/caribbeanwatch/src/pyRVPelagia64PE414Sababank_Current/mercator/update.py -j $TRAVIS_JOB_NUMBER --daily -r $REGION
#install:
#- docker build -t caribbeanwatch -f Dockerfile --build-arg TRAVIS_JOB_NUMBER="$TRAVIS_JOB_NUMBER" .

jobs:
  include:
    - stage: build
      script: 
      - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} -f Dockerfile --build-arg TRAVIS_JOB_NUMBER="$TRAVIS_JOB_NUMBER" .
      - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then mkdir -p $(dirname '/home/caribbeanwatch/src/pyRVPelagia64PE414Sababank_Current/cache/cache.tar.gz') ; docker save $(docker history -q ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} | grep -v '<missing>') | gzip > '/home/caribbeanwatch/src/pyRVPelagia64PE414Sababank_Current/cache/cache.tar.gz'; fi
      env: REGION=None
    - stage: deploy
      env: REGION=foo
      script: docker run -a stdout -t webpages ./update.sh "Automatic update to static site from travis CaribbeanWatch, jobid $TRAVIS_JOB_NUMBER"

stages:
  - build
  - test
  - deploy

