
# - NAME=Xenial-16.04-docker

env:
  # - NAME=caribbean_basin-daily
  # - NAME=caribbean_basin-ssh-daily
  # - NAME=curacao-daily
  # - NAME=curacao_regional-daily
  # - NAME=sababank-daily
  # - NAME=sintmaarten-daily

  - NAME=caribbean_basin-2h-1
  - NAME=caribbean_basin-2h-2
  # - NAME=caribbean_basin-ssh-2h
  # - NAME=curacao-2h
  # - NAME=curacao_regional-2h
  # - NAME=sababank-2h
  # - NAME=sintmaarten-2h

services: docker
dist: xenial
language: cpp
before_install:
- openssl aes-256-cbc -K $encrypted_149a08f8ff66_key -iv $encrypted_149a08f8ff66_iv -in store.tar.enc -out store.tar -d
- tar xvf store.tar
install: docker build -t caribbeanwatch -f Dockerfile --build-arg TRAVIS_JOB_NUMBER="$TRAVIS_JOB_NUMBER" .
script: docker run -a stdout -t caribbeanwatch /home/caribbeanwatch/src/pyRVPelagia64PE414Sababank_Current/mercator/update.py -j $TRAVIS_JOB_NUMBER -r $NAME 

jobs:
  include:
    - stage: combine
      env: NAME=caribbean_basin-2h
      services: docker
      dist: xenial
      language: cpp
      before_install:
      - openssl aes-256-cbc -K $encrypted_149a08f8ff66_key -iv $encrypted_149a08f8ff66_iv -in store.tar.enc -out store.tar -d
      - tar xvf store.tar
      install: docker build -t caribbeanwatch -f Dockerfile --build-arg TRAVIS_JOB_NUMBER="$TRAVIS_JOB_NUMBER" .
      script: docker run -a stdout -t caribbeanwatch /home/caribbeanwatch/src/pyRVPelagia64PE414Sababank_Current/mercator/update.py -j $TRAVIS_JOB_NUMBER -r $NAME 

#    - stage: deploy
#      env: NAME=webpages
#      services: docker
#      dist: xenial
#      language: cpp
#      before_install:
#      - openssl aes-256-cbc -K $encrypted_149a08f8ff66_key -iv $encrypted_149a08f8ff66_iv -in store.tar.enc -out store.tar -d
#      - tar xvf store.tar
#      install: docker build -t webpages -f Dockerfile_webupdate --build-arg TRAVIS_JOB_NUMBER="$TRAVIS_JOB_NUMBER" .
#      script: docker run -a stdout -t webpages ./update.sh "Automatic update to static site from travis CaribbeanWatch, jobid $TRAVIS_JOB_NUMBER"

stages:
  - test
  - combine
#  - deploy

